name: build
on: push

jobs:
  test:
    runs-on: ${{ matrix.os.runner }}
    name: ${{ matrix.os.name }} / OTP ${{matrix.beam.otp}} / Elixir ${{matrix.beam.elixir}}
    strategy:
      matrix:
        beam:
          - { otp: '25.0.2', elixir: '1.13.4' }
        os:
          - name: Linux
            runner: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.beam.otp }}
          elixir-version: ${{ matrix.beam.elixir }}
          version-type: strict

      - name: Retrieve Mix Dependencies Cache
        uses: actions/cache@v3
        id: mix-cache
        with:
          path: deps
          key: ${{ runner.os }}-${{ matrix.beam.otp }}-${{ matrix.beam.elixir }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - name: Install Mix dependencies
        if: steps.mix-cache.outputs.cache-hit != 'true'
        run: mix deps.get

      - name: mix format --check-formatted
        run: mix format --check-formatted

      - name: mix credo
        run: mix credo

      - name: mix dialyzer
        run: mix dialyzer

      - name: mix test
        run: mix test
